package health;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.awt.Font.BOLD;
import static java.awt.Font.ITALIC;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public final class PatientView extends JFrame {
  Connection connection = null;
  ResultSet resultSet = null;
  PreparedStatement preparedStatement = null;
  int requestID;
  String username;
  String userType;
  DefaultListModel<String> defaultListModel = new DefaultListModel<>();

  public PatientView(String patient) {
    initComponents();
    try {
      Class.forName("org.sqlite.JDBC");
      connection = DriverManager.getConnection("jdbc:sqlite:Health_Connect_DB");
      JOptionPane.showMessageDialog(null, "Connected");
    } catch (ClassNotFoundException | SQLException e) {
      JOptionPane.showMessageDialog(null, e);
    }
    username = patient;
    setUsername(patient);
    userType = "Patient";
    setUserType(userType);
    jList1.setVisible(false);
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public void setRequestID(int requestID) {
    this.requestID = requestID;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  private void initComponents() {
    JButton inProgressButton = new JButton();
    JButton closedButton = new JButton();
    JScrollPane jScrollPane1 = new JScrollPane();
    jList1 = new JList<>();
    JScrollBar jScrollBar1 = new JScrollBar();
    jLabel1 = new JLabel();
    JButton openRequest = new JButton();
    JLabel jLabel7 = new JLabel();
    JButton backButton = new JButton();
    JButton newButton = new JButton();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    inProgressButton.setText("In Progress Requests");
    inProgressButton.addActionListener(this::InProgressButtonActionPerformed);

    closedButton.setText("Closed Requests");
    closedButton.addActionListener(this::closedButtonActionPerformed);

    jList1.setModel(
        new AbstractListModel<>() {
          final String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

          public int getSize() {
            return strings.length;
          }

          public Object getElementAt(int i) {
            return strings[i];
          }
        });
    jScrollPane1.setViewportView(jList1);

    jLabel1.setFont(new Font("Eras Demi ITC", BOLD | ITALIC, 24));
    jLabel1.setText("Your Request History");

    openRequest.setText("Open Selected Request");
    openRequest.addActionListener(this::openRequestActionPerformed);

    jLabel7.setFont(new Font("Papyrus", BOLD, 14));
    jLabel7.setForeground(new Color(51, 51, 255));
    jLabel7.setText("HealthConnect");

    backButton.setText("Back");
    backButton.addActionListener(this::backButtonActionPerformed);

    newButton.setText("New Requests");
    newButton.addActionListener(this::newButtonActionPerformed);

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        jLabel1, GroupLayout.PREFERRED_SIZE, 513, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        LayoutStyle.ComponentPlacement.RELATED,
                        GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(
                        jLabel7, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE))
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        openRequest,
                                        GroupLayout.PREFERRED_SIZE,
                                        164,
                                        GroupLayout.PREFERRED_SIZE)
                                    .addGap(234, 234, 234)
                                    .addComponent(backButton))
                            .addComponent(
                                jScrollPane1,
                                GroupLayout.PREFERRED_SIZE,
                                703,
                                GroupLayout.PREFERRED_SIZE)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        newButton,
                                        GroupLayout.PREFERRED_SIZE,
                                        135,
                                        GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)
                                    .addComponent(inProgressButton)
                                    .addGap(67, 67, 67)
                                    .addComponent(closedButton)
                                    .addGap(115, 115, 115)))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        jScrollBar1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel7))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(
                                        jLabel1,
                                        GroupLayout.PREFERRED_SIZE,
                                        48,
                                        GroupLayout.PREFERRED_SIZE)))
                    .addGap(24, 24, 24)
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(inProgressButton)
                            .addComponent(closedButton)
                            .addComponent(newButton))
                    .addPreferredGap(
                        LayoutStyle.ComponentPlacement.RELATED,
                        GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(
                                jScrollBar1,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addComponent(
                                jScrollPane1, GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(openRequest)
                            .addComponent(backButton))
                    .addGap(19, 19, 19)));
    pack();
  }

  private void InProgressButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    jLabel1.setText("Your Opened Requests");
    jList1.setVisible(true);
    String element;
    String sql = "SELECT RID, Date FROM Request WHERE Status = ? AND PUsername = ?";
    defaultListModel.removeAllElements();
    element = "RID        Date";
    defaultListModel.addElement(element);
    try {
      preparedStatement = connection.prepareStatement(sql);
      preparedStatement.setString(1, "In Progress");
      preparedStatement.setString(2, username);
      resultSet = preparedStatement.executeQuery();
      if (resultSet.next()) {
        JOptionPane.showMessageDialog(null, "Username and Password is correct");
        element = resultSet.getString("RID") + "        " + resultSet.getString("Date");
        defaultListModel.addElement(element);
        while (resultSet.next()) {
          element = resultSet.getString("RID") + "        " + resultSet.getString("Date");
          defaultListModel.addElement(element);
        }
        jList1.setModel(defaultListModel);
      } else {
        JOptionPane.showMessageDialog(null, "No requests are in progress.");
      }
    } catch (SQLException | HeadlessException e) {
      JOptionPane.showMessageDialog(null, e);
    } finally {
      try {
        resultSet.close();
        preparedStatement.close();
      } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
      }
    }
  }

  private void newButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    jLabel1.setText("Your New Requests");
    jList1.setVisible(true);
    String element;
    String sql = "SELECT RID, Date FROM Request WHERE Status = ? AND PUsername = ?";
    defaultListModel.removeAllElements();
    element = "RID        Date";
    defaultListModel.addElement(element);
    try {
      preparedStatement = connection.prepareStatement(sql);
      preparedStatement.setString(1, "New");
      preparedStatement.setString(2, username);
      resultSet = preparedStatement.executeQuery();
      if (resultSet.next()) {
        JOptionPane.showMessageDialog(null, "Username and Password is correct");
        element = resultSet.getString("RID") + "        " + resultSet.getString("Date");
        defaultListModel.addElement(element);
        while (resultSet.next()) {
          element = resultSet.getString("RID") + "        " + resultSet.getString("Date");
          defaultListModel.addElement(element);
        }
        jList1.setModel(defaultListModel);
      } else {
        JOptionPane.showMessageDialog(null, "No new requests.");
      }
    } catch (SQLException | HeadlessException e) {
      JOptionPane.showMessageDialog(null, e);
    } finally {
      try {
        resultSet.close();
        preparedStatement.close();
      } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
      }
    }
  }

  private void closedButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    jLabel1.setText("Your Closed Requests");
    jList1.setVisible(true);
    String element;
    String sql = "SELECT RID, Date FROM Request WHERE Status = ? AND PUsername = ?";
    defaultListModel.removeAllElements();
    element = "RID        Date";
    defaultListModel.addElement(element);
    try {
      preparedStatement = connection.prepareStatement(sql);
      preparedStatement.setString(1, "Closed");
      preparedStatement.setString(2, username);
      resultSet = preparedStatement.executeQuery();
      if (resultSet.next()) {
        JOptionPane.showMessageDialog(null, "Username and Password is correct");
        element = resultSet.getString("RID") + "        " + resultSet.getString("Date");
        defaultListModel.addElement(element);
        while (resultSet.next()) {
          element = resultSet.getString("RID") + "        " + resultSet.getString("Date");
          defaultListModel.addElement(element);
        }
        jList1.setModel(defaultListModel);
      } else {
        JOptionPane.showMessageDialog(null, "No requests have been closed.");
      }
    } catch (SQLException | HeadlessException e) {
      JOptionPane.showMessageDialog(null, e);
    } finally {
      try {
        resultSet.close();
        preparedStatement.close();
      } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
      }
    }
  }

  private void backButtonActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    dispose();
    Profile profile = new Profile(username);
    profile.setVisible(true);
  }

  private void openRequestActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    if (jList1.getSelectedIndex() != -1) {
      String temp_requestID = jList1.getSelectedValue().toString();
      temp_requestID = temp_requestID.substring(0, 3);
      requestID = Integer.parseInt(temp_requestID);
      setRequestID(requestID);
      RequestConversation requestConversation =
          new RequestConversation(requestID, username, userType);
      dispose();
      requestConversation.setVisible(true);
    } else JOptionPane.showMessageDialog(null, "Please select a request");
  }

  public static void main(String[] args) {
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException
        | InstantiationException
        | IllegalAccessException
        | UnsupportedLookAndFeelException ex) {
      Logger.getLogger(PatientView.class.getName()).log(Level.SEVERE, null, ex);
    }

    final NewJFrame jFrame = new NewJFrame();

    EventQueue.invokeLater(() -> new PatientView(jFrame.getUsername()).setVisible(true));
  }

  // Variable declarations //
  private JLabel jLabel1;
  private JList jList1;
  // End of variables declaration //
}
